"""Add updated_at to watchlists

Revision ID: 3742b3f9b902
Revises: 
Create Date: 2025-06-24 05:42:14.628361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3742b3f9b902'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_stocks')
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('updated_at')

    op.create_table('watchlist_stocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('watchlist_id', sa.INTEGER(), nullable=True),
    sa.Column('ticker', sa.VARCHAR(length=20), nullable=True),
    sa.Column('added_at', sa.DATETIME(), nullable=True),
    sa.Column('price_alert_high', sa.FLOAT(), nullable=True),
    sa.Column('price_alert_low', sa.FLOAT(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
