"""Add tip_type and confidence to stock_tips

Revision ID: 497c478a5628
Revises: 3742b3f9b902
Create Date: 2025-06-24 10:33:00.860538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497c478a5628'
down_revision = '3742b3f9b902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping watchlist_stock table if it doesn't exist
    try:
        op.drop_table('watchlist_stock')
    except:
        pass
    
    # Add missing columns to stock_tips table
    try:
        op.add_column('stock_tips', sa.Column('tip_type', sa.String(length=10), nullable=True))
    except:
        pass
    
    try:
        op.add_column('stock_tips', sa.Column('confidence', sa.String(length=10), nullable=True))
    except:
        pass
    
    try:
        op.add_column('stock_tips', sa.Column('analysis', sa.Text(), nullable=True))
    except:
        pass
    
    try:
        op.add_column('stock_tips', sa.Column('user_id', sa.Integer(), nullable=True))
    except:
        pass
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column('stock_tips', 'user_id')
    except:
        pass
    
    try:
        op.drop_column('stock_tips', 'analysis')
    except:
        pass
    
    try:
        op.drop_column('stock_tips', 'confidence')
    except:
        pass
    
    try:
        op.drop_column('stock_tips', 'tip_type')
    except:
        pass
    
    # ### end Alembic commands ###

