"""Add notification models and tables

Revision ID: 7b5cf0d46cce
Revises: 497c478a5628
Create Date: 2025-06-30 00:54:51.309885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5cf0d46cce'
down_revision = '497c478a5628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_tips', schema=None) as batch_op:
        batch_op.alter_column('ticker',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('tip_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('confidence',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=10),
               nullable=False)
        batch_op.alter_column('analysis',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_stock_tips_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('expires_at')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('dislikes')
        batch_op.drop_column('price_target')
        batch_op.drop_column('direction')
        batch_op.drop_column('likes')
        batch_op.drop_column('reasoning')

    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('stock_tips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasoning', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('direction', sa.VARCHAR(length=4), nullable=True))
        batch_op.add_column(sa.Column('price_target', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('dislikes', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_stock_tips_user'), 'users', ['created_by_id'], ['id'])
        batch_op.alter_column('analysis',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('confidence',
               existing_type=sa.String(length=10),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('tip_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('ticker',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
