[providers]
python = "3.11"

[variables]
FLASK_ENV = "production"
PYTHONPATH = "/app"

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 main:app"
