[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python3 gunicorn_start.py"
healthcheckPath = "/health/ready"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
